* $$ JOB JNM=XXUSRAUD,DISP=D,CLASS=0                                            
* $$ LST LST=SYSLST,DISP=D,CLASS=Z                                              
// JOB    VUSRAUDT   Get Active Directory Attrs for Audit                       
// EXEC   PGM=VUSRAUDT,SIZE=*                                                   
/* EOD                                                                          
/& EOJ                                                                          
* $$ EOJ                                                                        
